--
-- CS157A
-- Project #1
--
--

-- db2 -tvf p1_create.sql

connect to cs157a;

drop table p1.account;
drop table p1.customer;

create table p1.customer (
  id      integer     not null generated by default as identity (start WITH 100, increment by 1, no cache),
  name    varchar(15) not null,
  gender  char        not null check (gender = 'M' or gender = 'F'),
  age     integer     not null check (age >= 0),
  pin     integer     not null check (pin >= 0),
  constraint pk_id primary key (id)
);

create table p1.account (
  number  integer     not null generated by default as identity (start WITH 1000, increment by 1, no cache),
  id      integer     not null,
  balance integer     not null check (balance >= 0),
  type    char        not null check (type = 'C' or type = 'S'),
  status  char        not null check (status = 'A' or status = 'I'),
  constraint pk_number primary key (number),
  constraint fk_id foreign key (id) references p1.customer(id) on delete cascade
);

terminate;

"SELECT ID, Name, Age, Gender, SUM(balance) AS Total_Balance FROM p1.customer JOIN p1.account ON p1.customer.id = p1.account.id"
 "SELECT ID, Name, Age, Gender, SUM(balance) AS Total_Balance FROM p1.customer NATURAL JOIN p1.account;"
 "SELECT ID, Name, Age, Gender, SUM(balance) AS Total_Balance FROM p1.customer NATURAL JOIN p1.account ORDER BY Total_Balance DESC"

"SELECT p1.customer.ID, Name, Age, p1.customer.Gender, SUM(balance) AS Total_Balance
"SELECT p1.customer.ID, Name, Gender, Age, SUM(balance) AS Total_Balance
FROM p1.customer, p1.account
WHERE p1.customer.id = p1.account.id
GROUP BY p1.customer.ID, name, gender, Age
ORDER BY Total_Balance DESC"
"
SELECT AVG(Total_Balance) AS Average
FROM(
    SELECT SUM(balance) AS Total_Balance, Age
    FROM p1.customer, p1.account
    WHERE p1.customer.id = p1.account.id
        and Age > 1 and Age < 100
    GROUP BY Age
)
"
